name: build

on: [push]

env:
  PACKER_VERSION: 1.5.5
  LIBARCHIVE_VERSION: 3.4.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # CODE
    - uses: actions/checkout@v2
    # TOOLS
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: '^1.14.1'
    # Caches
    - name: Current Month Var
      run: |
        echo "::set-output name=date::$(date +'%m-%Y')"
      id: cache
    - name: Cache libarchive build
      uses: actions/cache@v2.1.3
      with:
        path: ./libarchive-${{env.LIBARCHIVE_VERSION}}
        key: ${{ runner.os }}-libarchive-${{env.LIBARCHIVE_VERSION}}
    - name: Cache images
      uses: actions/cache@v2.1.3
      with:
        path: ./packer_cache
        key: ${{ runner.os }}-${{ steps.cache.outputs.date }}-packer_cache-1
    - name: Cache go mod
      uses: actions/cache@v2.1.3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Cache go build
      uses: actions/cache@v2.1.3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build

    # Installs
    - name: install libarchive
      shell: bash
      run: |
        sudo ./build-bsdtar.sh $LIBARCHIVE_VERSION
    - name: install deps
      shell: bash
      run: |
        sudo apt install qemu-user-static util-linux gdisk e2fsprogs
    - name: install packer and plugins
      shell: bash
      run: |
        ./build-packer.sh ${{ env.PACKER_VERSION }}

    - name: find qemu_binary
      shell: bash
      run: ls -la /usr/bin/ | grep qemu

    # Build
    - name: run packer
      shell: bash
      run: |
        sudo ./packer build -var-file ./hosts/raspi4/2gb.json packer.json

    # pack
    - name: archive + compress image
      shell: bash
      run: |
        tar --sparse -vczf raspberry-pi4.img.tar.gz ./raspberry-pi4.img
        md5sum raspberry-pi4.img.tar.gz > raspberry-pi4.img.tar.gz.md5

    # cleanup
    - name: cleanup cache
      shell: bash
      run: |
        sudo rm -rf packer_cache/*.lock

    # Upload
    - uses: actions/upload-artifact@v2.2.2
      with:
        name: raspberry-pi4.img.tar.gz
        path: raspberry-pi4.img.tar.gz
    - uses: actions/upload-artifact@v2.2.2
      with:
        name: raspberry-pi4.img.tar.gz.md5
        path: raspberry-pi4.img.tar.gz.md5
